site_name: My Documentation
theme:
  name: 'material'

markdown_extensions:
  - admonition  # Hộp ghi chú
  - pymdownx.details  # Mở rộng ghi chú
  - pymdownx.superfences  # Hỗ trợ code block nâng cao
  - pymdownx.highlight  # Làm đẹp code
  - pymdownx.inlinehilite  # Code inline
  - pymdownx.snippets  # Chèn file markdown
  - pymdownx.tabbed  # Tab trong tài liệu

nav:
  - Home: index.md
  - About: about.md
  - Material: material.md
  - COCI 2006 - 2007:
    - Contest 3:
      - Problem 1: coci0607/contest3/problem1.md
      - Problem 2: coci0607/contest3/problem2.md
      - Problem 3: coci0607/contest3/problem3.md
      - Problem 4: coci0607/contest3/problem4.md
      - Problem 5: coci0607/contest3/problem5.md
      - Problem 6: coci0607/contest3/problem6.md
    - Croatian Olympiad: 
      - Problem 1: coci0607/olympiad/problem1.md
      - Problem 2: coci0607/olympiad/problem2.md
      - Problem 3: coci0607/olympiad/problem3.md
      